// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLFzvyVzskvIXz4tm54PSkl1cPiTqv8cU',
    appId: '1:297773074836:web:0a037c4b339c0958d96781',
    messagingSenderId: '297773074836',
    projectId: 'spendwise-d2258',
    authDomain: 'spendwise-d2258.firebaseapp.com',
    storageBucket: 'spendwise-d2258.firebasestorage.app',
    measurementId: 'G-RDKWV1R07K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVdGRVtB0r-8hfUmHpoVc6fiWfaDSbMWE',
    appId: '1:297773074836:android:4171518a0ac94af2d96781',
    messagingSenderId: '297773074836',
    projectId: 'spendwise-d2258',
    storageBucket: 'spendwise-d2258.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzMxpzwmRoTLSObIW7Q1yIVmOpLTaY3HY',
    appId: '1:297773074836:ios:911ffcd2ac583bcbd96781',
    messagingSenderId: '297773074836',
    projectId: 'spendwise-d2258',
    storageBucket: 'spendwise-d2258.firebasestorage.app',
    iosBundleId: 'com.example.expenseManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzMxpzwmRoTLSObIW7Q1yIVmOpLTaY3HY',
    appId: '1:297773074836:ios:911ffcd2ac583bcbd96781',
    messagingSenderId: '297773074836',
    projectId: 'spendwise-d2258',
    storageBucket: 'spendwise-d2258.firebasestorage.app',
    iosBundleId: 'com.example.expenseManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLFzvyVzskvIXz4tm54PSkl1cPiTqv8cU',
    appId: '1:297773074836:web:07977ccc8b8f6e05d96781',
    messagingSenderId: '297773074836',
    projectId: 'spendwise-d2258',
    authDomain: 'spendwise-d2258.firebaseapp.com',
    storageBucket: 'spendwise-d2258.firebasestorage.app',
    measurementId: 'G-H1QZH9ECNM',
  );

}